### ISSUE TITLE
`clearSimEnv = TRUE` doesn't clear the `.mods` slot of `simList`(s)

### ISSUE THREAD

**Issue by CeresBarros** [PredictiveEcology/SpaDES.experiment#7]
`.mods` slot is not being fully cleaned with `clearSimEnv = TRUE`, as module functions (e.e.g event functions are functions sourced from module R/ folder) are still left. Because they are associated with the environment in which they are created, this generates `simList`s with potentially very large object sizes.

**Comment by CeresBarros** [comment]
Current workaround is to `rm(".mods", envir = simLists[[1]])`, where `simLists` is the output of `experiment(2)`, before saving it.

**Comment by eliotmcintire** [comment]
This is now implemented. `.mods` is now removed.
